cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
  path('', views.cart_detail, name='cart_detail'),
  path('add/<int:product_id>/', views.cart_add, name='cart_add'),
  path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

coupons/urls.py
from django.urls import path
from . import views


app_name = 'coupons'

urlpatterns = [
  path('apply/', views.coupon_apply, name='apply'),
]

orders/urls.py
from django.utils.translation import gettext_lazy as _
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
  path(_('create/'), views.order_create, name='order_create'),
  path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
  path('admin/order/<int:order_id>/pdf/', views.admin_order_pdf, name="admin_order_pdf"),
]

project/urls.py
from django.utils.translation import gettext_lazy as _
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from payment import webhooks

urlpatterns = i18n_patterns(
  path("admin/", admin.site.urls),
  path(_('cart/'), include('cart.urls', namespace='cart')),
  path(_('orders/'), include('orders.urls', namespace='orders')),
  path(_('payment/'), include('payment.urls', namespace='payment')),
  path(_('coupons/'), include('coupons.urls', namespace='coupon')),
  path("__reload__/", include("django_browser_reload.urls")),
  path('rosetta/', include('rosetta.urls')),
  path('', include('shop.urls', namespace="shop")),
)

urlpatterns += [
  path('payment/webhook/', webhooks.stripe_webhook, name='stripe-webhook'),
]


if settings.DEBUG:
  urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT,
  )

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
  path('', views.product_list, name='product_list'),
  path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
  path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

cart/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
  quantity = forms.TypedChoiceField(
    choices=PRODUCT_QUANTITY_CHOICES,
    coerce=int,
    label=_('Quantity'),
  )
  override = forms.BooleanField(
    required=False,
    initial=False,
    widget=forms.HiddenInput,
  )

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from .forms import CartAddProductForm
from coupons.forms import CouponApplyForm
from shop.models import Product
from .cart import Cart
from shop.recommender import Recommender


@require_POST
def cart_add(request, product_id):
  cart = Cart(request)
  product = get_object_or_404(Product, id=product_id)
  form = CartAddProductForm(request.POST)
  if form.is_valid():
    cd = form.cleaned_data
    cart.add(
      product=product,
      quantity=cd['quantity'],
      override_quantity=cd['override'],
    )
  return redirect("cart:cart_detail")


@require_POST
def cart_remove(request, product_id):
  cart = Cart(request)
  product = get_object_or_404(Product, id=product_id)
  cart.remove(product)
  return redirect('cart:cart_detail')


def cart_detail(request):
  cart = Cart(request)
  for item in cart:
    item['update_quantity_form'] = CartAddProductForm(initial={
      'quantity': item['quantity'],
      'override': True,
    })
  coupon_apply_form = CouponApplyForm()

  r = Recommender()
  cart_products = [item['product'] for item in cart]
  if (cart_products):
    recommended_products = r.suggest_products_for(cart_products, max_results=4)
  else:
    recommended_products = []

  return render(request, 'cart/detail.html', {
    'cart': cart,
    'coupon_apply_form': coupon_apply_form,
    'recommended_products': recommended_products,
  })

templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% load tailwind_filters %}

{% block title %}Your shoping cart{% endblock title %}

{% block content %}

<h1 class="text-center text-4xl text-pink-500 p-2 ">Your shoping cart</h1>
<div class="relative overflow-x-auto shadow-md sm:rounded-lg">
  <table class="w-full text-sm rtl:text-right text-gray-500 dark:text-gray-400 text-center">
      <thead class="text-xs text-gray-700 uppercase dark:text-gray-400">
          <tr>
              <th scope="col" class="px-6 py-3 bg-gray-50 dark:bg-gray-800">
                  Image
              </th>
              <th scope="col" class="px-6 py-3">
                  Product
              </th>
              <th scope="col" class="px-6 py-3 bg-gray-50 dark:bg-gray-800">
                  Quantity
              </th>
              <th scope="col" class="px-6 py-3">
                  Remove
              </th>
              <th scope="col" class="px-6 py-3">
                  Unit price
              </th>
              <th scope="col" class="px-6 py-3">
                  Price
              </th>
          </tr>
      </thead>
      <tbody>
      {% for item in cart %}
      {% with product=item.product %}
          <tr class="border-b border-gray-200 dark:border-gray-700">
              <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap bg-gray-50 dark:text-white dark:bg-gray-800">
                <a href="{{ product.get_absolute_url }}">
                  <img src="
                  {% if product.image %}
                    {{ product.image.url }}
                  {% else %}
                    {% static "img/no_image.png" %}  
                  {% endif %}
                  " class="w-[150px] h-[150px] object-contain mx-auto rounded-full shadow-sm shadow-blue-700">
                </a>
              </th>
              <td class="px-6 py-4">
                {{ product.name }}
              </td>
              <td class="px-6 py-4 bg-gray-50 dark:bg-gray-800">
                <form action="{% url "cart:cart_add" product.id %}" method="post">
                  <div class="*:rounded-lg [&]:text-blue-900">
                    {{ item.update_quantity_form.quantity }}
                  </div>
                  {{ item.update_quantity_form.override }}
                  <input type="submit" value="Update" class="px-2 py-1 mt-2 bg-purple-800 rounded-md hover:bg-purple-600 hover:text-white cursor-pointer">
                  {% csrf_token %}
                </form>
              </td>
              <td class="px-6 py-4">
                <form action="{% url "cart:cart_remove" product.id %}" method="post">
                  <input type="submit" value="Remove" class="px-3 py-2 text-black font-bold bg-red-600 rounded-lg hover:bg-red-400 cursor-pointer">
                  {% csrf_token %}
                </form>
              </td>
              <td class="px-6 py-4 bg-gray-50 dark:bg-gray-800">
                ${{ item.price }}
              </td>
              <td>
                ${{ item.total_price }}
              </td>
          </tr>
          {% endwith %}
          {% endfor %}


          {% if cart.coupon %}
            <tr class="border border-gray-200 dark:border-gray-700">
              <td class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap  dark:text-white">Subtotal</td>
              <td colspan="4"></td>
              <td>${{ cart.get_total_price|floatformat:2 }}</td>
            </tr >  
            <tr class="border border-gray-200 dark:border-gray-700"> 
              <td class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap  dark:text-white">
                "<span class="text-yellow-400 text-lg">{{ cart.coupon.code }}</span>" coupon
                ({{ cart.coupon.discount }}% off)
              </td>
              <td colspan="4"></td>
              <td class="text-rose-500">
                - ${{ cart.get_discount|floatformat:2 }}
              </td>
            </tr>
          {% endif %}
          <tr class="border-b border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-800">
            <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap  dark:text-white">
              Total
            </th>
            <td colspan="4" class="px-6 py-4">
                  
            </td>
            <td class="px-6 py-4">
              ${{ cart.get_total_price_after_discount|floatformat:2 }}
            </td>
          </tr>
      </tbody>
  </table>

  {% if recommended_products %}
    <div class="recommendations cart">
      <h3>People who bought this also bought</h3>
      <div class="flex flex-wrap">
        {% for p in recommended_products %}
        <div class="p-2 m-2 bg-neutral-800  text-center hover:shadow-lg hover:shadow-blue-300">
          <div class="item">
            <a href="{{ p.get_absolute_url }}">
              <img src="{% if p.image %}{{ p.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}" class="w-[150px] h-[150px] rounded-full object-cover object-top">
            </a>
            <p>
              <a href="{{ p.get_absolute_url }}" class="text-blue-500 text-lg">{{ p.name }}</a>
            </p>
          </div>
          </div>
        {% endfor %}
      </div>
    </div>
  {% endif %}

  <div class="border-2 border-green-800 p-3 rounded-lg my-2">
    <p>Apply a coupon:</p>
    <form action="{% url "coupons:apply" %}" method="post">
      {% csrf_token %}
      <div class="w-2/12">
        {{ coupon_apply_form|crispy }}
      </div>
      <input type="submit" value="Apply" class="px-3 py-2 bg-rose-800 hover:bg-rose-600 rounded-lg cursor-pointer">
    </form>
</div>
</div>
<br>
<p>
  <div class="text-right">
    <a href="{% url "shop:product_list" %}" class="px-3 py-2 text-white font-bold bg-blue-600  hover:bg-blue-400 rounded-s-lg">Continue shopping</a>
    <a href="{% url "orders:order_create" %}" class="px-3 py-2 text-white font-bold bg-green-600  hover:bg-green-400  rounded-e-lg">Checkout</a>
  </div>
</p>
{% endblock content %}