cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
  path('', views.cart_detail, name='cart_detail'),
  path('add/<int:product_id>/', views.cart_add, name='cart_add'),
  path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

payment/urls.py
from django.utils.translation import gettext_lazy as _
from django.urls import path
from . import views, webhooks

app_name = 'payment'

urlpatterns = [
  path(_('process/'), views.payment_process, name='process'),
  path(_('completed/'), views.payment_completed, name='completed'),
  path(_('canceled/'), views.payment_canceled, name='canceled'),
]

project/urls.py
from django.utils.translation import gettext_lazy as _
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from payment import webhooks

urlpatterns = i18n_patterns(
  path("admin/", admin.site.urls),
  path(_('cart/'), include('cart.urls', namespace='cart')),
  path(_('orders/'), include('orders.urls', namespace='orders')),
  path(_('payment/'), include('payment.urls', namespace='payment')),
  path(_('coupons/'), include('coupons.urls', namespace='coupon')),
  path("__reload__/", include("django_browser_reload.urls")),
  path('rosetta/', include('rosetta.urls')),
  path('', include('shop.urls', namespace="shop")),
)

urlpatterns += [
  path('payment/webhook/', webhooks.stripe_webhook, name='stripe-webhook'),
]


if settings.DEBUG:
  urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT,
  )

payment/models.py
from django.db import models

# Create your models here.

payment/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.conf import settings
from decimal import Decimal
import stripe
from orders.models import Order

stripe.api_key = settings.STRIPE_SECRET_KEY
stripe.api_version = settings.STRIPE_API_VERSION


def payment_completed(request):
  return render(request, 'payment/completed.html')


def payment_canceled(request):
  return render(request, 'payment/canceled.html')


def payment_process(request):
  order_id = request.session.get('order_id', None)
  order = get_object_or_404(Order, id=order_id)
  if request.method == 'POST':
    success_url = request.build_absolute_uri(reverse('payment:completed'))
    cancel_url = request.build_absolute_uri(reverse('payment:canceled'))
    session_data = {
      'mode': 'payment',
      'client_reference_id': order.id,
      'success_url': success_url,
      'cancel_url': cancel_url,
      'line_items': [],
    }

    for item in order.items.all():
      session_data['line_items'].append({
        'price_data': {
          'unit_amount': int(item.price * Decimal('100')),
          'currency': 'usd',
          'product_data': {
            'name': item.product.name,
          },
        },
        'quantity': item.quantity,
      })

    if order.coupon:
      stripe_coupon = stripe.Coupon.create(
        name=order.coupon.code,
        percent_off=order.discount,
        duration='once',
      )
      session_data['discounts'] = [{
        'coupon': stripe_coupon.id,
      }]

    session = stripe.checkout.Session.create(**session_data)
    return redirect(session.url, code=303)
  else:
    return render(request, 'payment/process.html', locals())

templates/payment/canceled.html
{% extends "shop/base.html" %}

{% block title %}Payment canceled{% endblock title %}

{% block content %}
  <h1 class="text-center text-4xl text-pink-500 p-2 ">Your payment has not been processed</h1>

  <div class="col-span-2 ms-5 bg-slate-800 rounded-lg p-5 ">
      <p class="text-2xl text-center text-amber-500">There was a problem processing your payment.</p>
  </div>
{% endblock content %}

templates/payment/completed.html
{% extends "shop/base.html" %}

{% block title %}Payment successful{% endblock title %}

{% block content %}
  <h1 class="text-center text-4xl text-pink-500 p-2 ">Your payment was successful</h1>

  <div class="col-span-2 ms-5 bg-slate-800 rounded-lg p-5 ">
      <p class="text-2xl text-center text-amber-500">Your payment has been placed successfully.</p>
  </div>
{% endblock content %}

templates/payment/process.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}Pay your order{% endblock title %}

{% block content %}
  <h1 class="text-center text-4xl text-pink-500 p-2 ">Order summary</h1>

  <div class="col-span-2 ms-5 bg-slate-800 rounded-lg p-5 ">

    <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
      <table class="w-full text-sm text-center rtl:text-right text-gray-500 dark:text-gray-400">
          <thead class="text-xs text-gray-700 uppercase dark:text-gray-400 bg-blue-800">
              <tr>
                  <th scope="col" class="px-6 py-3 ">
                      Image
                  </th>
                  <th scope="col" class="px-6 py-3">
                      Product
                  </th>
                  <th scope="col" class="px-6 py-3 ">
                      Price
                  </th>
                  <th scope="col" class="px-6 py-3">
                      Quantity
                  </th>
                  <th scope="col" class="px-6 py-3">
                      Total
                  </th>
              </tr>
          </thead>
          <tbody>
          {% for item in order.items.all %}
              <tr 
              class="border-b border-gray-200 text-white
               {% comment %} {% if forloop.counter|divisibleby:"2" %}bg-gray-800 {% else %}bg-gray-700{% endif %} {% endcomment %}
              {% cycle "bg-gray-800" "bg-gray-700" %}"
              >
                  <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap ">
                      <img src="
                      {% if item.product.image %}
                        {{ item.product.image.url }}
                      {% else %}
                        {% static "img/no_image.png" %}  
                      {% endif %}
                      " class="w-[150px] h-[150px] object-contain">
                  </th>
                  <td class="px-6 py-4">
                    {{ item.product.name }}
                  </td>
                  <td class="px-6 py-4 ">
                   ${{ item.price }}
                  </td>
                  <td class="px-6 py-4">
                   {{ item.quantity }}
                  </td>
                  <td class="px-6 py-4 ">
                    ${{ item.get_cost }}
                  </td>
              </tr>
              {% endfor %}

              {% if order.coupon %}
                <tr class="border-b border-gray-200 dark:border-gray-700 bg-blue-800">
                  <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap  dark:text-white">
                    Subtotal
                  </th>
                  <td colspan="3"></td>
                  <td class="px-6 py-4">
                      ${{ order.get_total_cost_before_discount|floatformat:2 }}  
                  </td>
                </tr>
                <tr class="border-b border-gray-200 dark:border-gray-700 ">
                  <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap  dark:text-white">
                    "{{ order.coupon.code }}" coupon
                    ({{ order.discount }}% off)
                  </th>
                  <td colspan="3"></td>
                  <td class="px-6 py-4">
                    - ${{ order.get_discount|floatformat:2 }}  
                  </td>
               </tr>
              {% endif %}

              <tr class="border-b border-gray-200 dark:border-gray-700 bg-blue-800">
                <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap  dark:text-white">
                  Total
                </th>
                <td colspan="3"></td>
                <td class="px-6 py-4">
                    ${{ order.get_total_cost|floatformat:2 }}  
                </td>
              </tr>

          </tbody>
      </table>
    </div>

    <br>
    
  <form action="{% url "payment:process" %}" method="post">
    {% csrf_token %}
    <input type="submit" value="Pay now" class="bg-blue-800 hover:bg-blue-700 font-bold px-5 py-2 m-2 rounded-md">
  </form>
  </div>
{% endblock content %}